const colors = {
  light: {
    text: "#0a0a0f",
    tint: "#FF4B2B",
    background: "#F5F5FA",
    foreground: "#0a0a0f",
    card: "#FFFFFF",
    cardForeground: "#0a0a0f",
    primary: "#FF4B2B",
    primaryForeground: "#FFFFFF",
    secondary: "#EFEFF7",
    secondaryForeground: "#1a1a28",
    muted: "#EFEFF7",
    mutedForeground: "#6B6B7E",
    accent: "#00C9A7",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0EC",
    input: "#E0E0EC",
    surface: "#FFFFFF",
    surfaceElevated: "#F5F5FA",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF4B2B",
    background: "#0A0A0F",
    foreground: "#FFFFFF",
    card: "#1A1A26",
    cardForeground: "#FFFFFF",
    primary: "#FF4B2B",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A26",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A26",
    mutedForeground: "#9090A8",
    accent: "#00C9A7",
    accentForeground: "#0A0A0F",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#28283A",
    input: "#28283A",
    surface: "#13131E",
    surfaceElevated: "#1A1A26",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 14,
};

export default colors;
